# Generated by Django 5.0.6 on 2024-09-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_productimages_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='life',
            field=models.CharField(blank=True, default='100', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='mfd',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
